ViewModels/TotalPointsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AcademyManager.ViewModels
{
    public class TotalPoints
    {
        public string TraineeId { get; set; }
        public double TotalPoint { get; set; }
    }

    public class TotalPointsViewModel
    {
        public int CourseId { get; set; }
        public List<TotalPoints> Points { get; set; }
    }
}

Controllers/TraineesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AcademyManager.Contracts;
using AcademyManager.Models;
using AcademyManager.ViewModels;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AcademyManager.Controllers
{
    [Authorize(Roles = "Trainee")]
    public class TraineesController : Controller
    {
        private readonly UserManager<AMUser> _userManager;
        private readonly IMapper _mapper;
        private readonly ICoursesRepository _coursesRepository;
        private readonly IScoresRepository _scoresRepository;
        private readonly ITestsAndExamsRepository _testsAndExamsRepository;

        public TraineesController(UserManager<AMUser> userManager,
            IMapper mapper, ICoursesRepository coursesRepository,
            IScoresRepository scoresRepository, ITestsAndExamsRepository testsAndExamsRepository)
        {
            _userManager = userManager;
            _mapper = mapper;
            _coursesRepository = coursesRepository;
            _scoresRepository = scoresRepository;
            _testsAndExamsRepository = testsAndExamsRepository;
        }
        // GET: Students
        public async Task<IActionResult> Index()
        {
            var users = await _userManager.GetUsersInRoleAsync("Trainee");
            var model = _mapper.Map<IList<AMUser>, IList<TraineesVM>>(users);
            return View(model);
        }

        public IActionResult CourseList()
        {
            var courses = _coursesRepository.FindAll().ToList();
            var model = _mapper.Map<List<CourseVM>>(courses);
            return View(model);
        }

        public IActionResult GeneralCourseDetails(int courseId)
        {
            var courseTestsAndExams = _testsAndExamsRepository.GetTestsAndExamsByCourseId(courseId).ToList();
            var scoresList = new List<CurrentTestOrExamVM>();
            if (courseTestsAndExams.Count > 0)
            {
                for (int i = 0; i < courseTestsAndExams.Count; i++)
                {
                    var scores = _scoresRepository.GetScoreByTestOrExamId(courseTestsAndExams[i].Id).ToList();
                    if (scores.Count > 0 )
                    {
                        var scoreModel = _mapper.Map<List<ScoresVM>>(scores);
                        var selected = new CurrentTestOrExamVM
                        {
                            TestOrExamId = courseTestsAndExams[i].Id,
                            Scores = scoreModel
                        };
                        scoresList.Add(selected);
                    }
                    else
                    {
                        continue;
                    }
                }
            }
            var model = new GeneralCourseDetailsVM
            {
                CourseId = courseId,
                TestsOrExams = scoresList
            };
            return View(model);
        }

        public IActionResult PersonalCourseDetails(int courseId)
        {
            var courseTestsOrExams = _testsAndExamsRepository.GetTestsAndExamsByCourseId(courseId).ToList();
            var scores = new List<ScoresVM>();
            var trainee = _userManager.GetUserAsync(User).Result;
            if (courseTestsOrExams.Count > 0)
            {
                for (int i = 0; i < courseTestsOrExams.Count; i++)
                {
                    var score = _scoresRepository.GetScoreByTestAndExamIdAndTraineeId(courseTestsOrExams[i].Id, trainee.Id);
                    if (score != null)
                    {
                        var scoreModel = _mapper.Map<ScoresVM>(score);
                        scores.Add(scoreModel);
                    }
                    else
                    {
                        continue;
                    }
                }
            }
            var model = new PersonalCourseDetailsVM
            {
                CourseId = courseId,
                Scores = scores
            };
            return View(model);
        }

        [AllowAnonymous]
        [Authorize(Roles = "Trainee, Facilitator")]
        public IActionResult TotalPoints(int courseId)
        {
            var testsAndExams = _testsAndExamsRepository.GetTestsAndExamsByCourseId(courseId).ToList();
            var allScores = new List<List<Scores>>();
            int courseTotal = 0;
            foreach (var item in testsAndExams)
            {
                var scores = _scoresRepository.GetScoreByTestOrExamId(item.Id).ToList();
                courseTotal += item.Total;
                allScores.Add(scores);
            }
            
            var trainees = new List<string>();
            foreach (var item in allScores)
            {
                foreach (var scoreSet in item)
                {
                    if (!trainees.Contains(scoreSet.TraineeId))
                    {
                        trainees.Add(scoreSet.TraineeId);
                    }
                    else
                    {
                        continue;
                    }
                }
            }

            var traineePoints = new List<TotalPoints>();
            foreach (var item in trainees)
            {
                double total = 0;
                foreach (var scoreSet in testsAndExams)
                {
                    var score = _scoresRepository.GetScoreByTestAndExamIdAndTraineeId(scoreSet.Id, item);
                    if (score == null)
                    {
                        total += 0;
                    }
                    else
                    {
                        total += score.Score;
                    }
                }
                var average = (total / courseTotal) * 100;
                var totalTraineePoint = new TotalPoints
                {
                    TraineeId = item,
                    TotalPoint = Math.Round(average, 2)
                };
                traineePoints.Add(totalTraineePoint);
            }
            var model = new TotalPointsViewModel
            {
                CourseId = courseId,
                Points = traineePoints
            };
            return View(model);
        }

        public IActionResult Result()
        {
            var trainee = _userManager.GetUserAsync(User).Result;
            var traineeScores = _scoresRepository.GetScoresByTraineeId(trainee.Id).ToList();
            var traineeCourses = new List<int>();

            foreach (var item in traineeScores)
            {
                var testOrExam = _testsAndExamsRepository.FindById(item.TestOrExamId);
                var course = _coursesRepository.FindById(testOrExam.CourseId);
                if (traineeCourses.Contains(course.Id))
                {
                    continue;
                }
                else
                {
                    traineeCourses.Add(course.Id);
                }
            }

            var traineeResult = new List<TotalCourseScoreVM>();

            foreach (var item in traineeCourses)
            {
                double totalScore = 0;
                var totalMark = 0;
                var testOrExams = _testsAndExamsRepository.GetTestsAndExamsByCourseId(item).ToList();
                for (int i = 0; i < testOrExams.Count; i++)
                {
                    totalMark += testOrExams[i].Total;
                    var score = _scoresRepository.GetScoreByTestAndExamIdAndTraineeId(testOrExams[i].Id, trainee.Id);
                    if (score != null)
                    {
                        totalScore += score.Score;
                    }
                }

                var averageScore = (totalScore / totalMark) * 100;
                var courseScore = new TotalCourseScoreVM
                {
                    CoureId = item,
                    TotalScore = Math.Round(averageScore, 2)
                };
                traineeResult.Add(courseScore);
            }
            var model = traineeResult;
            return View(model);
        }
    }
}

Views/Trainees/CourseList.cshtml
@model IEnumerable<AcademyManager.ViewModels.CourseVM>
@inject UserManager<AMUser> userManager
@{
    ViewData["Title"] = "CourseList";
}

    <div class="container-fluid">
        <h1 class="text-center">Course List</h1>

        <div class="card">
            <div class="card-body">
                <table id="tblList" class="table">
                    <thead>
                        <tr>
                            <th>
                                Course Name
                            </th>
                            <th>
                                Course Facilitator
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CourseName)
                                </td>
                                @if (item.FacilitatorId != null)
                                {
                                    var facilitator = userManager.FindByIdAsync(item.FacilitatorId).Result;
                                    <td>
                                        @facilitator.FirstName @facilitator.LastName @facilitator.MiddleName
                                    </td>
                                }
                                else
                                {
                                    <td></td>
                                }
                            <td>
                                <a asp-action="GeneralCourseDetails" asp-route-courseId="@item.Id" class="btn m-2 bg-gradient-lightblue text-light">General Course Details</a>
                                <a asp-action="PersonalCourseDetails" asp-route-courseId="@item.Id" class="btn m-2 bg-gradient-indigo text-light">Personal Course Details</a>
                                <a asp-action="TotalPoints" asp-route-courseId="@item.Id" class="btn m-2 bg-gradient-dark text-light">Total Points</a>
                            </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="card-footer text-center">
                <a asp-controller="Trainees" asp-action="Result" class="btn btn-secondary">View Result</a>
            </div>
        </div>
    </div>

Views/Trainees/GeneralCourseDetails.cshtml
@model GeneralCourseDetailsVM
@inject AcademyManager.Contracts.IScoresRepository scoresRepo
@inject AcademyManager.Contracts.ITestsAndExamsRepository testsAndExamsRepo
@inject AcademyManager.Contracts.ICoursesRepository coursesRepo
@inject UserManager<AMUser> user
@{
    ViewData["Title"] = "GeneralCourseDetails";
    var course = coursesRepo.FindById(Model.CourseId);
}

    <div class="container-fluid">

        <h1 class="text-center">@course.CourseName Details</h1>

        @if (Model.TestsOrExams.Count > 0)
        {
            <div class="row">
                @foreach (var item in Model.TestsOrExams)
                {
                    <div class="card col-sm-6 mb-2 col-12">
                        @{
                            var testOrExam = testsAndExamsRepo.FindById(item.TestOrExamId);
                        }
                        <div class="card-header">
                            <h4 class="card-title"><b>@testOrExam.TestOrExamName</b></h4>
                        </div>
                        <div class="card-body">
                            <table class="table tblList">
                                <thead>
                                    <tr>
                                        <th>Trainee</th>
                                        <th>Score (@testOrExam.Total)</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{
                                        var scores = item.Scores;
                                        for (int i = 0; i < scores.Count; i++)
                                        {
                                            var trainee = user.FindByIdAsync(scores[i].TraineeId).Result;

                                            <tr>
                                                <td><b>@trainee.FirstName @trainee.LastName @trainee.MiddleName</b></td>
                                                <td>@scores[i].Score</td>
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                }
            </div>
            <a class="btn btn-info" asp-action="TotalPoints" asp-route-courseId="@Model.CourseId">
                Total Points
            </a>
        }
        else
        {
            <h3 class="text-warning">No Tests or Exams for this course yet</h3>
        }
    </div>

Views/Trainees/Index.cshtml
@model IEnumerable<AcademyManager.ViewModels.TraineesVM>

@{
    ViewData["Title"] = "Index";
}
    <div class="col-12">
        <h1>Trainees List</h1>

        <div class="card">
            <div class="card-body">
                <table id="tblList" class="table">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.TraineeId)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.FirstName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.MiddleName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.LastName)
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TraineeId)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.FirstName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.MiddleName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.LastName)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>

    </div>

Views/Trainees/PersonalCourseDetails.cshtml
@model PersonalCourseDetailsVM
@inject AcademyManager.Contracts.IScoresRepository scoresRepo
@inject AcademyManager.Contracts.ITestsAndExamsRepository testsAndExamsRepo
@inject AcademyManager.Contracts.ICoursesRepository coursesRepo
@{
    ViewData["Title"] = "PersonalCourseDetails";
    var course = coursesRepo.FindById(Model.CourseId);
}

    <div class="container-fluid">
        <h1 class="text-center">@course.CourseName Personal Details</h1>

        @if (Model.Scores.Count > 0)
        {
            <div class="card">
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                @foreach (var item in Model.Scores)
                                {
                                    var testOrExam = testsAndExamsRepo.FindById(item.TestOrExamId);
                                    <th>
                                        @testOrExam.TestOrExamName
                                    </th>
                                }
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                @foreach (var item in Model.Scores)
                                {
                                    <td>
                                        @item.Score
                                    </td>
                                }
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        }
        else
        {
            <h3 class="text-warning">No scores in any tests or exams for you yet in @course.CourseName</h3>
        }
    </div>

Views/Trainees/Result.cshtml
@model List<TotalCourseScoreVM>
@inject UserManager<AMUser> userManager
@inject AcademyManager.Contracts.ICoursesRepository courseRepo
@{
    ViewData["Title"] = "Result";
    var trainee = userManager.GetUserAsync(User).Result;
    var pictureUrl = "~/images/" + (trainee.PictureUrl ?? "noimage.png");
    var coursesTotal = 0;
    double traineesTotal = 0;
}

@if (Model.Count > 0)
{
    <div class="card" id="result">
        <div class="card-header text-center">
            <div class="bg-gradient-indigo p-2">
                <h2 class="text-white">Fintrak Academy Result</h2>
            </div>
            <h4>@trainee.FirstName @trainee.MiddleName @trainee.LastName</h4>

            <img class="card-img-top" src="@pictureUrl" asp-append-version="true" style="height: 120px; width: auto;" />
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            Course
                        </th>
                        <th>
                            Points
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        coursesTotal += 100;
                        traineesTotal += item.TotalScore;
                        var course = courseRepo.FindById(item.CoureId);
                        <tr>
                            <td>
                                @course.CourseName
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TotalScore)
                            </td>
                        </tr>
                    }
                    <tr>
                        <td>
                            <b>Total Points</b>
                        </td>
                        <td>
                            @{
                                traineesTotal = Math.Round(traineesTotal, 2);
                                <i><b>@traineesTotal</b> out of <b>@coursesTotal</b></i>
                            }
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="card">
        <div class="card-footer text-center">
            @*<input class="btn btn-primary" type="button" value="Download Result" id="btnPrint" />*@
            <button class="btn btn-primary" id="btnPrint" onclick="printResult()">Print Result</button>
        </div>
    </div>
}
else
{
    <div>
        <h3 class="text-warning">No result for you yet</h3>
    </div>
}
@section Scripts{
    <script type="text/javascript">
        function printResult() {
           window.print();
        }
    </script>
}

Views/Trainees/TotalPoints.cshtml
@model TotalPointsViewModel
@inject UserManager<AMUser> user
@inject AcademyManager.Contracts.ICoursesRepository courseRepo
@{
    ViewData["Title"] = "TotalPoints";
    var course = courseRepo.FindById(Model.CourseId);
}

    <div class="container-fluid">
        <h1 class="text-center">@course.CourseName Total Points</h1>

        <div class="card">
            <div class="card-body">
                <table id="tblList" class="table">
                    <thead>
                        <tr>
                            <th>
                                Trainee
                            </th>
                            <th>
                                Points
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Points)
                        {
                            
                            var trainee = user.FindByIdAsync(item.TraineeId).Result;
                            <tr>
                                <td>
                                    @trainee.FirstName @trainee.MiddleName @trainee.LastName
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TotalPoint)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            @if (User.IsInRole("Facilitator"))
            {
                <div class="card-footer">
                    <a class="btn btn-info" asp-controller="Facilitators" asp-action="ViewCourseDetails" asp-route-courseId="@Model.CourseId">
                        Back to course Details
                    </a>
                </div>
            }
        </div>
    </div>